### ISSUE TITLE
Transition gh-pages codeblocks to backticks

### ISSUE THREAD

**Issue by subsidel** [bbc/tal#353]
Related to #352

We should update our documentation pages to use backtick code blocks over {% highlight %} style ones, as per recommendation in the github blog below: 
https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by dhurrell** [comment]
:+1:

**Comment by kukulaka** [comment]
Closing issue due to[ deprecation](https://github.com/bbc/tal#deprecation-announcement-12122022).
