### ISSUE TITLE
Base device class is missing some functions

### ISSUE THREAD

**Issue by jamiemm** [bbc/tal#386]
antie/devices/device.js does not contain definitions for several functions that are actually only implemented in antie/devices/browserdevice.js. These include, for example, clearElement, setElementContent, cloneElement 

These functions are used in several places in the code base where the JsDoc says that it only requires the device interface.

This could break a lot of widgets etc if another device was created that did not explicitly use the browserdevice class.

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward. This means that this bug will not be investigated. 

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
