### ISSUE TITLE
Show/hide methods on widget do not have return values

### ISSUE THREAD

**Issue by bastuijnman** [bbc/tal#395]
Hi guys,

`antie/widgets/widget` contains both a `show` and `hide` method, which according to the JSDoc should return boolean values for whether or not the animation was called. These methods, however, do not return any explicit value (except for the default undefined).

My proposal would be to return the animation reference so developers could cancel show/hide animations when needed, is this something which would be agreeable with you guys? In that case I can make a PR for this.

Kind regards,

Bas Tuijnman
24i

**Comment by tsadler1988** [comment]
Hi Bas,

This is fine from our point of view, so feel free to raise a PR.

Ideally, the animation object returned would be newly created object (following functional principles) but this is not a must.

Tom

**Comment by bastuijnman** [comment]
Hi Tom,

In this case we can just do `return device.hideElement(options)` right?

Cheers,

Bas

**Comment by tsadler1988** [comment]
That looks right to me yes.

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
