### ISSUE TITLE
Nested ComponentContainers prevent full component lifecycle

### ISSUE THREAD

**Issue by jonpbbc** [bbc/tal#405]
There’s a problem if your project nests component containers. You can have a situation where a component container, A, can show a component container, B, which then shows a component C. Then A hides B. B receives the `afterhide` event, and can do `this.removeChildWidgets()`. However, this does not clear the widgets associated with C from memory; they are still being referenced from C, which is itself referenced from the `knownComponents` array. The `afterhide` event from B will bubble only up the tree (and then only assuming propagation isn't stopped) and so, unless B is explicitly written to hide C when it is itself hidden, C does not receive the hide events in the component lifecycle. Even if A then re-shows B and B re-shows C; the `beforerender` event and other show events will be called on C each time, but it never receives the hide events.

Not only is this a potential memory leak for your system, any timers, video streams,  or asynchronous requests that you may have set up with clear-down in the hide events won’t have that logic called, which may be a source of other bugs in your system.

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
