### ISSUE TITLE
How do I map TVs against configs?

### ISSUE THREAD

**Issue by EloB** [bbc/tal#409]
I've read that I need a database to map user agents against brand and models. How can I get that? What's the point with this library if that data isn't open source? 👎

**Comment by bastuijnman** [comment]
The point of the frameworks is to not let developers worry about device implementation logic by only calling implemented interfaces.

Deploying applications can be done multiple ways, either you just generate a build artifact for a specific device (config), or do it dynamically by building your own database of devices that you want to support.

Find out which user-agents are being sent by the devices and you can use a server side language to serve the correct device config.

**Comment by tsadler1988** [comment]
We are now using https://github.com/bbc/melanite along with https://github.com/bbc/device-identification-data to map user agents to TAL configs.

Our service that uses melanite is also open source (https://github.com/bbc/matterhorn), but is probably best used as an example implementation, as is quite specific to our architecture.
