### ISSUE TITLE
GitHub pages documentation on mobile

### ISSUE THREAD

**Issue by tsadler1988** [bbc/tal#416]
Our GitHub pages don't look right on mobile. 

http://fmtvp.github.io/tal/widgets/working-with-widgets.html in particular overlaps the content with the side nav:
![image](https://cloud.githubusercontent.com/assets/5602024/20546505/6f14aa44-b10d-11e6-8993-f289515d703a.png)

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward. Unfortunatly this means that this bug will not be fixed with the documentation. 

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
