### ISSUE TITLE
Mediaplayer `getSeekableRange` method throws TypeError

### ISSUE THREAD

**Issue by sanderlooijenga** [bbc/tal#423]
Hi guys,

In theory the use of the `getSeekableRange` method in the `'antie/devices/mediaplayer/mediaplayer'` could resolve in a TypeError, because it could possibly return `undefined` (e.g. see `getSeekableRange` method in `'antie/devices/mediaplayer/html5'`). In some methods (like `_getClampedTime`) it's expected that the `getSeekableRange` method returns an object containing `start` and `end` as keys. Therefore referencing these keys while `undefined` is being returned, results in a TypeError.

Is there something we should do about this?

Kind regards,

Sander Looijenga
24i

**Comment by tsadler1988** [comment]
Hi Sander,

Good spot! 

I think we are protected by the fact that we only utilise the seekable range when we know it is available. For example, in HTML5 we do not make any calls to `_getClampedTime` until we have received the `loadedmetadata` event.

However, I agree that it would be a good thing to protect against this, perhaps by defaulting range to `start: undefined, end: undefined`?

Tom

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward. Therefore this bug will not be fixed. 

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
