### ISSUE TITLE
Problem with Carousel component

### ISSUE THREAD

**Issue by peterjtracey** [bbc/tal#424]
UPDATE: Solved the spacing problem, was just a problem with the size of some of the images added to the carousel. But the event problem remains. The second carousel actually fires the select event of the first carousel, and I suspect the left and right events are also going to the first carousel, they don't do anything with the new one.

I have code that leads to a working Carousel component. It renders properly and navigation with left/right arrows plus select all work. I copied that code for use for a different purpose, and now the carousel flashes (sometimes) for a very brief time at the top of the window then reappears far down the page. The code for the component is as follows:

```
require.def("n2me/appui/components/mediamenu",
    [
        "antie/widgets/component",
        "antie/widgets/button",
        "antie/widgets/label",
        "antie/widgets/image",
        "antie/datasource",
        "antie/widgets/carousel",
        "n2me/appui/components/mediaformatter",
        "n2me/appui/components/mediafeed",
        "antie/widgets/carousel/strips/wrappingstrip",
        "antie/widgets/carousel/navigators/wrappingnavigator",
        "antie/widgets/carousel/binder",
        "antie/widgets/carousel/keyhandlers/activatefirsthandler"
    ],
    function (Component, Button, Label, Image, DataSource, Carousel, MediaFormatter, MediaFeed,
        WrappingStrip,
        WrappingNavigator, Binder, ActivateFirstHandler) {
        
        // All components extend Component
        return Component.extend({
            init: function () {
                console.log("COMPONENT");

                var self, mediaFormatter, mediaFeed, image;

                self = this;
                // It is important to call the constructor of the superclass
                this._super("mediamenu");
                
                image = new Image("topstrip", "static/script/appui/images/OverhangSliceHD.jpg")

                this.appendChildWidget(image);

                mediaFormatter = new MediaFormatter();
                mediaFeed = new MediaFeed();
                
                // Create a DataSource, this uses the feed to get data and presents it to the formatter
                this._dataSource = new DataSource(this, mediaFeed, "loadData");
                
                // do the bind (and build the carousel's items)
                this._binder = new Binder(mediaFormatter, this._dataSource);

                // Create a new carousel with the formatter
                this._carousel = new Carousel("mediacarousel", Carousel.orientations.HORIZONTAL);

                this._carousel.setWidgetStrip(WrappingStrip);
                this._carousel.setNavigator(WrappingNavigator);

                var handler = new ActivateFirstHandler();
                handler.attach(this._carousel);

                // Add it to the component
                this.appendChildWidget(this._carousel);
                
                this._binder.appendAllTo(this._carousel);

                this.addEventListener("beforerender", function (ev) {
                    self._onBeforeRender(ev);
                });

                this._carousel.addEventListener("select", function (evt) {
                    var device = RuntimeContext.getDevice();
    
                    var storage = device.getStorage(StorageProvider.STORAGE_TYPE_SESSION, "n2me");
                    storage.setItem("categoryindex", selectedIndex);                
                });

                var selectedIndex = 0;
                this._carousel.addEventListener("afteralign", function (evt) {
                    selectedIndex = evt.alignedIndex;
                });
            },

            // Appending widgets on beforerender ensures they're still displayed
            // if the component is hidden and subsequently reinstated.
            _onBeforeRender: function () {
            } 
        });
    }
);
```

I don't understand why this code works for one case and breaks badly for the other. Please help!

**Comment by stasandrichuk** [comment]
The issue that the second carousel fires the first carousel's events fixed. 
It seems that the issue is obviously caused because the first carousel's eventlistners have not been removed before the second carousel is created. 

So I removed the first carousel's eventlistners before the second carousel pushed to the app:
In mainmenu.js file
`self._carousel._eventListeners.keydown = [];
  self.getCurrentApplication().pushComponent(
      "maincontainer",
      "n2me/appui/components/mediamenu"
  ); `

But though the first carousel's eventlistners are removed, there still exists the issue that the second carousel's key events do not fire though the keydown event listener is added to the carousel events list.

So I added keydown eventlistener to document and defined the progress of the carousel according to keycodes. And the below code is update from the above one that Peter posted:
In mediamenu.js file
`require.def("n2me/appui/components/mediamenu",
    [
        "antie/widgets/component",
        "antie/widgets/button",
        "antie/widgets/label",
        "antie/widgets/image",
        "antie/datasource",
        "antie/widgets/carousel",
        "n2me/appui/components/mediaformatter",
        "n2me/appui/components/mediafeed",
        "antie/widgets/carousel/strips/wrappingstrip",
        "antie/widgets/carousel/navigators/wrappingnavigator",
        "antie/widgets/carousel/binder",
        'antie/widgets/carousel/keyhandlers/keyhandler',
        "antie/widgets/carousel/keyhandlers/activatefirsthandler",
        'antie/runtimecontext',
        'antie/storageprovider'
    ],
    function (Component, Button, Label, Image, DataSource, Carousel, MediaFormatter, MediaFeed,
        WrappingStrip,
        WrappingNavigator, Binder, ActivateFirstHandler, RuntimeContext, StorageProvider) {
        
        // All components extend Component
        return Component.extend({
            init: function () {
                console.log("COMPONENT");

                var self, mediaFormatter, mediaFeed, image;

                self = this;
                // It is important to call the constructor of the superclass
                this._super("mediamenu");
                
                image = new Image("topstrip", "static/script/appui/images/OverhangSliceHD.jpg");

                this.appendChildWidget(image);

                mediaFormatter = new MediaFormatter();
                mediaFeed = new MediaFeed();
                
                // Create a DataSource, this uses the feed to get data and presents it to the formatter
                this._dataSource = new DataSource(this, mediaFeed, "loadData");
                
                // do the bind (and build the carousel's items)
                this._binder = new Binder(mediaFormatter, this._dataSource);

                // Create a new carousel with the formatter
                this._carousel = new Carousel("mediacarousel", Carousel.orientations.HORIZONTAL);

                this._carousel.setWidgetStrip(WrappingStrip);
                this._carousel.setNavigator(WrappingNavigator);

                // Add a keydown EventListener for Carousel 
                var previousKey, nextKey, carousel;
                carousel = this._carousel;
                previousKey = carousel.orientation().defaultKeys().PREVIOUS;
                nextKey = carousel.orientation().defaultKeys().NEXT;
                document.addEventListener('keydown', function (ev) {    
                    switch (ev.keyCode) {
                    case previousKey:
                        if (carousel.previousIndex() !== null) {
                            carousel.completeAlignment();
                            carousel.alignPrevious(carousel._animationOptions);
                            ev.stopPropagation();
                        }
                        break;
                    case nextKey:
                        if (carousel.nextIndex() !== null) {
                            carousel.completeAlignment();
                            carousel.alignNext(carousel._animationOptions);
                            ev.stopPropagation();
                        }
                        break;
                    }
                    carousel.setActiveChildIndex(carousel._aligner._lastAlignIndex);
                });

                // Add it to the component
                this.appendChildWidget(this._carousel);
                
                this._binder.appendAllTo(this._carousel);

                this.addEventListener("beforerender", function (ev) {
                    self._onBeforeRender(ev);
                });

                this.addEventListener("aftershow", function appReady() {
                    self.getCurrentApplication().ready();
                    self.removeEventListener('aftershow', appReady);
                    self.removeEventListener('aftershow', _addKeyListeners);
                });
                
                this._carousel.addEventListener("select", function (evt) {
                    console.log("select2");
                    var device = RuntimeContext.getDevice();
    
                    var storage = device.getStorage(StorageProvider.STORAGE_TYPE_SESSION, "n2me");
                    var token = storage.getItem("regtoken");

                    if (token && token.length > 0) {

                    } else {
                        self.getCurrentApplication().pushComponent("maincontainer", "n2me/appui/components/regscreen");
                    }
                });

                var selectedIndex = 0;
                this._carousel.addEventListener("afteralign", function (evt) {
                    selectedIndex = evt.alignedIndex;
                });

            },

            // Appending widgets on beforerender ensures they're still displayed
            // if the component is hidden and subsequently reinstated.
            _onBeforeRender: function () {
            } 
        });
    }
);`

I hope it will be helpful.
However I wonder why the second carousel doesn't work when the keydown event is added to it and works only when it is added to document. Are there any better solutions?

Thanks - Alex

**Comment by tsadler1988** [comment]
If the carousel is not receiving keydown events, then neither it nor any of its child widgets are focussed. 

The application receives the keydown event, and calls bubbleEvent on the focussed widget. If you put a break point here - https://github.com/bbc/tal/blob/master/static/script/application.js#L297 - you should see which widget is focussed, and therefore which keydown event listeners are being called.

It is possible that a child widget is focussed, and has an event listener that is stopping propagation to the carousel.

**Comment by subsidel** [comment]
@peterjtracey Are you still facing this issue?

**Comment by subsidel** [comment]
@peterjtracey Are you still facing this issue?
