### ISSUE TITLE
Keyboard: DEL key not highlighted when 'delete' pressed on remote control

### ISSUE THREAD

**Issue by onionfx-work** [bbc/tal#425]
Hi,
Triple tapping numbers on the remote control highlights the related keys (a-z, 0-9, SPACE) correctly.

However pressing 'delete' on the remote control does not highlight the DEL key onscreen.

I have a simple fix for this.
Inside keyboard, _onKeyDownHandler there is a separate case for VK_BACK_SPACE and I'm simply setting the active child key (exactly how it is done when you reach the maximum allowed length of input).

```javascript
} else if(evt.keyCode === KeyEvent.VK_BACK_SPACE) {
    if(this._currentText.length > 0) {
        this.setActiveChildKey('-');
        ...
```

I think I have this (whole) line ready with some tests :)

Thanks,
Sam

**Comment by subsidel** [comment]
As per @tsadler1988 comments on #426 I believe this behaviour to be intentional. So I'm going to mark this as an enhancement.

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
