### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by subsidel** [bbc/tal#431]
The github pages links and an image are broken in the readme, likely due to repo being moved from fmtvp to bbc.

**Comment by dhurrell** [comment]
Fixed apart from the Travis build status, which presumably requires the new repo location to be set up in Travis.

**Comment by tsadler1988** [comment]
Not sure if Travis resynced automatically and picked up the repo org move, or if I caused a resync by logging into Travis myself. Either way, seems to work now.

**Comment by AlexChesters** [comment]
@tsadler1988 Travis resyncs every 24 hours so it was probably that :)

**Comment by tsadler1988** [comment]
#437 raised to fix broken links in other areas of repo.
