### ISSUE TITLE
Keyboard: Triple tapping at max length is inconsistent

### ISSUE THREAD

**Issue by onionfx-work** [bbc/tal#434]
If you fill a keyboard to its maximum length.
Then single press a triple tap key it is ignored (though focus etc. is called on the keyboard)
If you continue tapping the same key, the last character is removed and you can cycle through the full sequence of keys associated with that triple tap group.

e.g.
Keyboard set to max length of 5
Configure '2' to triple tap as ['a','b','c']
Enter 'eeeee' into keyboard
Press '2' twice

The last 'e' is replaced by 'b'

I suggest these inputs should be ignored

**Comment by tsadler1988** [comment]
Closed by #435.
