### ISSUE TITLE
Encrypted HLS support 

### ISSUE THREAD

**Issue by adityaj221** [bbc/tal#436]
HI,

I've been playing with the TAL for a while now, and have been able to create an app out of it.
However, I've hit a roadblock trying to figure out if TAL supports encrypted HLS.

We have the videos as encrypted HLS which needs to be decrypted on the fly by the player using the key while making the request for the source file.

However from the documentation its a bit unclear if this is supported.

Can you please guide me with this if it is supported or not in TAL and if yes, a guidance to the path that needs to be followed.

Thanks.

**Comment by tsadler1988** [comment]
Hi @adityaj221,

We do not have anything in TAL to provide encrypted HLS support, but the underlying device browser may well support it.

If we were to provide support, it would require integration with Media Source Extensions, which is not supported by all devices, including CEHTML and Samsung Maple devices. 

It is therefore unlikely that TAL will ever provide encrypted HLS support, and you will always need to rely on the underlying device browser to support it.

Tom

**Comment by tsadler1988** [comment]
Assume my answer covers this off - closing.
