### ISSUE TITLE
How BBC Tal Apps run on actual devices?

### ISSUE THREAD

**Issue by Himanshu-Gurung** [bbc/tal#465]
Greetings All,

I have recently developed an app using the service, and the documentation & forums helped me a lot in this. Right now I am concerned how will the app actually runs on the **Televisions**. I have gone through documentation, as we have to manage the device config files. But how should the app work on televisions, is it something like we have to publish the app same as google play store or appstore. 

Thanks in Advance,
Himanshu

**Comment by premjoy7** [comment]
Yes, you're correct. App needs to be packaged for stores separately, eg. Samsung, LG, etc. For more details on distribution, please refer below links:

Tizen store overview:
https://developer.tizen.org/distribution/tizen-store-overview

LG app submission process:
http://webostv.developer.lge.com/distribute/app-submission-process/

**Comment by Himanshu-Gurung** [comment]
Thank you for responding with the detailed descriptions. I guess I have to work separately for each store/manufacturers.

**Comment by rosswilson** [comment]
Hi Himanshu,

@premjoy7 is correct, the process for getting your new app onto televisions and other devices involves forming an relationship with each manufacturer or platform.

Some manufacturers have a formalised application process, others will involve a more traditional business partnership.

Each device manufacturer can give further guidance, specific to their platform.

**Comment by Himanshu-Gurung** [comment]
Hello @rosswilson ,

Thank you for the update. I came across one more issue. I will create a new thread so that it doesn't messes up the discussions here.
