### ISSUE TITLE
Numeric keys for samsung tv remote not working

### ISSUE THREAD

**Issue by priya0510** [bbc/tal#466]
how to enable numeric keys for samsung tv remote ?

**Comment by rosswilson** [comment]
Hi @priya0510

TAL has the concept of device configuration files, where one config exists for each device type that you want to target. These device configs contain, amongst other things, a key mapping that translates the device-specific key codes to ones TAL understands.

Check that your app is using the correct device configuration when running on a Samsung device.

There’s more information here: http://bbc.github.io/tal/overview/device-configuration.html
