### ISSUE TITLE
How to use component as widget (without pushing)?

### ISSUE THREAD

**Issue by jaikumartj** [bbc/tal#467]
in default program, there is a program (carousel component) and we want to use that as widget.

**Comment by rosswilson** [comment]
Hello jaikumartj, could you clarify your question for me? Maybe a code example or some more context can help me understand what you're trying to do.

**Comment by jaikumartj** [comment]
In sample TAL project, there is component (carouselcomponent) which provides a working carousel element and i want to use it like widget instead of component.

NOTE: I've tried to convert it into widget but there is one problem in data source. If i am using an API call inside data source file its working fine but if i use a simple data feed without API then its not working, how to solve that 

compoent - [carouselcomponent - Copy.txt](https://github.com/bbc/tal/files/1591534/carouselcomponent.-.Copy.txt)

Widget - [carouselcomponent1.txt](https://github.com/bbc/tal/files/1591549/carouselcomponent1.txt)

SimpleFeed - [simplefeed.txt](https://github.com/bbc/tal/files/1591555/simplefeed.txt)

**Comment by jaikumartj** [comment]
Could you tell me how to create a scrollable grid ?

**Comment by subsidel** [comment]
A scrolling grid can be implemented by creating a carousel of carousels.
https://github.com/bbc/tal/issues/463#issuecomment-352193048

I've expanded the carousel examples to hopefully help answer both these questions:
https://github.com/bbc/talexample/blob/bc930cf65a8c6507f739a52529ba1d0b758287d6/static/script/appui/components/componentwithscrollinggridwidget.js#L18

https://github.com/bbc/talexample/blob/bc930cf65a8c6507f739a52529ba1d0b758287d6/static/script/appui/components/scrollinggridwidget.js

**Comment by jaikumartj** [comment]
Thank you, its working fine. 
But grid is supposed to scroll all the rows not just single row and focus from one row to another is also not proper(i.e if l'm at 1st row 4th element and when I press down then focus should go to 2nd row 4th element)

**Comment by jaikumartj** [comment]
Is there any way to make grid widget to be scrollable?

**Comment by subsidel** [comment]
I feel this is somewhat offtopic of this issue, so I've created a new one #469
