### ISSUE TITLE
Scrollable Grids.

### ISSUE THREAD

**Issue by subsidel** [bbc/tal#469]
Creating issue for this comment.
https://github.com/bbc/tal/issues/467#issuecomment-354415914

**Comment by jaikumartj** [comment]
Instead of creating carousel inside carousel, how to make a grid itself scrollable?

**Comment by subsidel** [comment]
The [Grid](http://bbc.github.io/tal/jsdoc/antie.widgets.Grid.html) is a static component that does not move at all and has no inbuilt mechanism for doing so.

If scrolling needs to happen on either the x or the y axis then you should use [VerticalList](http://bbc.github.io/tal/jsdoc/antie.widgets.VerticalList.html) or [HorizontalList](http://bbc.github.io/tal/jsdoc/antie.widgets.HorizontalList.html) components within a carousel, where the carousel provides the scrolling.

If the whole grid must move on _both_ the x *and* y axis then you will need to do this yourself using [animators](http://bbc.github.io/tal/widgets/animation.html) and listening for [key events](http://bbc.github.io/tal/overview/events.html)
