### ISSUE TITLE
How to set a culling strip for horizontal carousel

### ISSUE THREAD

**Issue by jaikumartj** [bbc/tal#470]
In sample project, carouselComponent has a method called " setcarouselnavigatorandwidgetstrip() " which sets different types of widget strip.
how to implement such methods for horizontal carousel (ie.to use CULLING mode in horizontal carousel)

**Comment by subsidel** [comment]
The example application is already doing this.

You set the Carousel orientation to `Carousel.orientations.HORIZONTAL` and then call `setWidgetStrip` on the carousel, passing in `CullingStrip` component.

This will set up the carousel to be horizontal and using a culling strip.

http://bbc.github.io/tal/widgets/carousel.html
https://github.com/bbc/talexample/blob/master/static/script/appui/components/carouselcomponent.js#L105

**Comment by jaikumartj** [comment]
instead of using that example application, i've created a carosel and used setwidgetStrip(CullingStrip). I'm not getting any output. should i add anything else to make a culling strip in carousel

**Comment by jaikumartj** [comment]
[scrollinggridwidget.txt](https://github.com/bbc/tal/files/1618541/scrollinggridwidget.txt)
To this component I'm trying to add a culling strip, but I'm not getting any output

**Comment by jaikumartj** [comment]
I'm trying to create horizontal carousels inside vertical carousel with culling widgetstrip but I'm not getting any output because of the function setwidgetStrip (). How to solve this?

**Comment by subsidel** [comment]
If using these strips it is compulsory to set widget lengths before performing an alignment. It may also be necessary to set the ‘Mask length’ (the size of the mask opening). Normally this length is measured from the DOM, but if the DOM is not ready when the first carousel alignment is made, then no items will be displayed unless the mask length has been explicitly set beforehand.

**Comment by jaikumartj** [comment]
we tried to create the  carousels of carousel as in the below formatter and we tried to set widget length as well but still there is no output
[test_carousel_formatter.txt](https://github.com/bbc/tal/files/1625193/test_carousel_formatter.txt)

**Comment by bastuijnman** [comment]
You're overriding the widget strip you just populated by doing: 
```
this._carousel.setWidgetStrip(CullingStrip);
```

I suggest doing it directly after creating the carousel itself.

**Comment by jaikumartj** [comment]
we tried to set length and culling strip right after the creation of carousel, we are not getting any output

**Comment by jaikumartj** [comment]
we are trying to create a nested carousel(like a grid) and want both to be in culling. If it is working for you, please send us code

**Comment by bastuijnman** [comment]
We can't really know what you're doing based on only the formatter code. We have nested carousels without any problem, but that's all business code that we're not going to share.

The only real problem that I saw in your shared code was that the widget strip was overwritten at the end of end of the format function, if that's not the problem then it's somewhere else in your own logic. I would suggest setting breakpoints in your code to see whether your carousel is actually filling with the data you want.

If you don't have your editor/IDE connected to your browser then this is an easy way to do so:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger

**Comment by jaikumartj** [comment]
we are getting the output only if we dont set CullingStrip for inner carousel. we wanted both outer and inner carousel to have CullingStrip. 
carousel component is vertical carousel and we have commented "todo" in certain lines, it takes in carousel formatter and that creates horizontal carousel. the formatter for horizontal carousel is simple formatter.
we want both the carousel to be in culling. please refer to these files


[test_carousel_formatter.txt](https://github.com/bbc/tal/files/1625570/test_carousel_formatter.txt)
[test_carousel_simple_fromatter.txt](https://github.com/bbc/tal/files/1625571/test_carousel_simple_fromatter.txt)
[test_carousel_component.txt](https://github.com/bbc/tal/files/1625572/test_carousel_component.txt)

**Comment by bastuijnman** [comment]
You're still setting the culling strip last in the `test_carousel_formatter.txt` file

**Comment by jaikumartj** [comment]
we tried to set even after the carousel declaration line, still it is not working

**Comment by bastuijnman** [comment]
Then set debugger statements after every important to see what's going on in the carousels themselves to figure out what's going wrong. Maybe there is something wrong with your datasource calls, maybe there is something wrong with the order of setting the carousel, who knows.

There is just too much going on in your code samples to see what's going on.

**Comment by basimman** [comment]
Hi bastuijnman, 
   I am also facing the same issue, Nested carousel is not working, when I set it to CULLING strip. Is it possible to share the sample nested carousel formatter with us. I have followed the way mentioned in the document to create the Culling carousel, but no use with setting mask height and widgets length.

**Comment by deepak-pk** [comment]
Hi i had the same problem. i was not attaching Button to the carousal formatter. once i added a button type to the Formatter.format returned object it works. hope it helps.

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
