### ISSUE TITLE
Does BBC Tal supports WebP images?

### ISSUE THREAD

**Issue by Himanshu-Gurung** [bbc/tal#471]
Greetings To All,

I am requested to use webp images in BBC tal app. So am I be able to do so !!!

Thanks In Advance,
Himanshu

**Comment by subsidel** [comment]
Hi @Himanshu-Gurung,

The only image types we currently use ourselves are:
* PNG (ARGB 32bit)
* GIF with animation.
* JPEG

You may be able to webp as the `Image` component is just rendering an `<img>`, however we haven't tested this ourselves and webp support is limited, even in desktop browsers.

https://caniuse.com/#feat=webp
