### ISSUE TITLE
Implementation of keyboard 

### ISSUE THREAD

**Issue by Arunprasanth** [bbc/tal#482]
Do we have any sample application which shows the implementation of keyboard in bbc/tal ? 
I have tried it using the below code 
```
var myVirtualKeyBoard = new Keyboard("keyboards", 13,2, "abcdefghijklmnopqrstuvwxyz", false, true);
               myVirtualKeyBoard.setActiveChildKey('A')
  this.appendChildWidget(myVirtualKeyBoard);
```
But this is not showing a keyboard , instead it shows 13*2(column *row) number of buttons in the screen. I couldn't get any column/row design , all the data are coming as rows. 
Can someone help me on this issue ? 
Please share if anybody has a sample for the same

**Comment by tsadler1988** [comment]
You're defining your keys in lower case, but then using upper case to reference them (`myVirtualKeyBoard.setActiveChildKey('A')`). Looking at the implementation, this is case sensitive, so I'd suggest you try fixing that and see if it resolves your issue.

**Comment by Arunprasanth** [comment]
@tsadler1988  Thanks for your replay. I have tried to change the code based on your comment but nothing got changed. Still it is showing letters in row by row. 
```
 var myVirtualKeyBoard = new Keyboard("keyboards", 13, 2, "ABCDEFGHIJKLMNOPQRSTUVWXYZ", false, true);
               myVirtualKeyBoard.setActiveChildKey('A')
 this.appendChildWidget(myVirtualKeyBoard);
```

This is what my new code is.

**Comment by tsadler1988** [comment]
@Arunprasanth can you share the DOM structure? It should look something like this:

![image](https://user-images.githubusercontent.com/5602024/36682443-fe866b7a-1b12-11e8-9745-de153ad54c21.png)

And then inside the row:

![image](https://user-images.githubusercontent.com/5602024/36682485-1bfec5ee-1b13-11e8-93eb-e018b066d2f1.png)

**Comment by tsadler1988** [comment]
@Arunprasanth your DOM looks correct, so I can only assume that this is a CSS issue.

It looks like you're using the TAL example app as a base. I believe there are styles around the `.listitem` CSS class that might be causing it to be displayed incorrectly, but it could easily be some other CSS causing your issue.

**Comment by Arunprasanth** [comment]
@tsadler1988  Thank you for pointing out the issue. I will look into it.

**Comment by Arunprasanth** [comment]
@tsadler1988  Hi, I couldn't find any class named keyboard in the base.css file in the given sample application. Could you please share a keyboard style class if you have ?

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
