### ISSUE TITLE
How can I create HTML controls like textbox, textarea, dropdown etc using bbc/tal ?

### ISSUE THREAD

**Issue by Arunprasanth** [bbc/tal#483]
Hi , 
Is there any way to create HTML controls using bbc/tal . I have appended html controls to maincontainer using javascript but I cannot get focus on those items. 

` $("#maincontainer").append( "<div> First name: <input type='text' name='fname'><br>Last name: <input type='text' name='lname'><br></div>" );`
Please find the attached screenshot. 
![capture](https://user-images.githubusercontent.com/17898273/36578821-b2387504-1885-11e8-832f-4fba1fd83f14.PNG)

**Comment by Haroon-KA** [comment]
Hi @Arunprasanth , 

We faced a similar issue where we needed HTML text input in our application. We created a new widget by extending the TAL widget class.

Thanks,

**Comment by rosswilson** [comment]
Hi @Arunprasanth,

We don't tend to use the native form controls like `<input ... />` as that relies on native device support, which varies a lot. Some devices will show a native onscreen keyboard, other devices won't.

What we recommend is using the TAL Keyboard widget to provide an onscreen keyboard. Then respond to the keypress events to populate a simple widget to display the user's input.

**Comment by Arunprasanth** [comment]
@rosswilson  Sure I will do the same
