### ISSUE TITLE
Native DRM support

### ISSUE THREAD

**Issue by nefcarvalho** [bbc/tal#486]
Hi,
I understand that TAL does not support DRM from third-party vendors like Nagra or Verimatrix.
Considering that Samsung has native support for Playready, does TAL support it or will developer need to add support for that?

Best,
Nuno

**Comment by rosswilson** [comment]
Hello,

There is no support for DRM within TAL, so additional work would be needed to integrate with a third-party vendor.

I'm not sure how involved the integration would be for your chosen vendor, but please do get back in touch if there are any TAL changes needed that'd make your integration easier.

**Comment by alaghusun60** [comment]
Whether BBC tal can work Express player drm. If not means any drm it support

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
