### ISSUE TITLE
Build bbctal application for XBOX 1

### ISSUE THREAD

**Issue by Arunprasanth** [bbc/tal#487]
I have to build a bbctal application for xbox 1, for that I am trying to create a Universal Windows Platform from bbctal code. Do we have any documentations or samples for the same ? 
Any help will be appreciated. 
Thanks in advance.

**Comment by rosswilson** [comment]
Hello @Arunprasanth,

I don't believe there are any public docs for building a UWP app wrapper around a TAL application. However, if you create a web-wrapper UWP app, then that is actually a very similar environment to run your app. You just specify the URL to your web app launch page.

There's some good resources for doing this:

* https://channel9.msdn.com/Events/Build/2016/B888
* https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/samples

**Comment by Arunprasanth** [comment]
@rosswilson Thanks for your quick replay. I went through the documents but I couldn't find any solutions which work with tal framework. I could create a normal javascript app and make it UWP. We dont have any html pages in tal instead mustache we have, so do we build the app to get the corresponding html files and a min version of javascript files  to work with UWP ? or any other ways can we do the same ?

**Comment by rosswilson** [comment]
I'd recommend treating the UWP wrapper like any other device; where you're loading your TAL app via the device's browser.

There's some docs here that describe the HTML entry-point needed to launch a TAL app: http://bbc.github.io/tal/getting-started/tutorial/createanindex.html

Your UWP app manifest will specify the URL needed to load your app. When a user launches your UWP app it'll make a HTTP request to the specified URL. Your backend server serves up a HTML app that specifies a path to load your JS, which then boots your app.

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
