### ISSUE TITLE
Sample app not working on TV

### ISSUE THREAD

**Issue by nefcarvalho** [bbc/tal#488]
Hi,
We are trying to run the TAL example (https://github.com/bbc/talexample) on a Samsung Smart TV (model UE40F6320 - Orsay), but without success. The app is installed and when launched on TV it gets the screen "Loading TALdemo...." and stays forever.

We have already tested different devices configuration from the config devices folder, but the results are the same.

Any ideas on how to overcome this problem?

Best,
Nuno

PS: We already upgraded the TV firmware, factory settings reset and Smart Hub reset.

**Comment by Arunprasanth** [comment]
Hi, Which sample you are using ? Hello world ?Is it working  in the computer browser ?

**Comment by nefcarvalho** [comment]
Hi,
The sample we are using is available at https://github.com/bbc/talexample. It’s working in the browser using the default webkit configuration (default-webkit-default.json).

**Comment by seksky333** [comment]
Same issue here as well. Not sure how to get it to worked on a Samsung Smart TV

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
