### ISSUE TITLE
how to create a hyphen in bbctal keyboard ?

### ISSUE THREAD

**Issue by Arunprasanth** [bbc/tal#490]
I need to append a hyphen(-),underscore(_) characters in keyboard, but when I try to do the same it  shows as a DEL key for hyphen and line break for underscore
In the keyboard widget code _populateTheGridWithKeyButtons method checks for this condition and set letter as DEL if it match with a hyphen. So is there any way to include hyphen in keyboard ?? 

Note : as a temporary solution i have included hypehn and underscore like ' _ ' ,' - ' . (adding spaces after and before character) and detect those key press in the keydown event and remove the spaces in this character and append it to _currentText. But i believe there will be more good solution for this.

**Comment by tsadler1988** [comment]
Hi @Arunprasanth,

I'm afraid it looks like the keyboard was designed with only letters and numbers taken into consideration. If you want to fix this, I would suggest you duplicate `keyboard.js` and find a new way to represent DELETE and SPACE keys in the keyboard. Perhaps `keys` should be an array rather than a string?

Thanks,

Tom

**Comment by Arunprasanth** [comment]
@tsadler1988  Thanks for the input, but anyway I have created keyboard with hyphen and underscore in a tricky way that I have mentioned in the question itself.

**Comment by tsadler1988** [comment]
OK thanks @Arunprasanth. I will leave this issue open for information and in case anyone wants to create a keyboard v2.

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward. 

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
