### ISSUE TITLE
Focus not getting back when we use keyboards and buttons together in a vertical list.

### ISSUE THREAD

**Issue by Arunprasanth** [bbc/tal#491]
I have created a vertical list and added 2 buttons and one keyboard in to it. Focus is working fine when I navigate between buttons but when focus comes to keyboard then I cannot navigate back to any of the buttons. Is there any way to resolve this issue ? 
Please find my example from [example](https://github.com/Arunprasanth/talkeyboard)

Note : as a temporary solution now I am  detecting the up/down key event in keyboard and using  `listWidget.getChildWidgets()[index].focus();`  to get focus 
Thanks & Regards , 
Arunprasanth KV

**Comment by tsadler1988** [comment]
Hi @Arunprasanth,

I think your issue is that you have enabled vertical wrapping of the keyboard:
```
myVirtualKeyBoard = new Keyboard("Keyboard", 23, 2 ,keys, true , true);
```
The 6th parameter sets vertical wrapping to `true`. So when you press UP or DOWN to focus away from the keyboard, it will instead wrap to the bottom or top row of the keyboard respectively.

**Comment by Arunprasanth** [comment]
@tsadler1988  Thnaks for your response

**Comment by kukulaka** [comment]
Closing as issue has been answered.

We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
