### ISSUE TITLE
Navigation from keyboard widget to horizontallist

### ISSUE THREAD

**Issue by Haroon-KA** [bbc/tal#498]
Hi, 

I am having a component, with vertical list component. In the vertical list, I am having a keyboard and couple of other buttons in a horizontalList. I am passing the focus to keyboard on load and then on pressing the down arrow key the keyboard buttons are getting selected. Once I reaching the last row in keyboard, the control is not getting transferred to the horizontalList. Can someone please help. 

Thanks,

**Comment by m0hamm3d-ac** [comment]
The focus will move to the horizontal list only if both keyboard and horizontallist are added to the vertical list. Can you double check your code and confirm if the appendChildWidget function on vertical list has been called twice? - once with keyboard and once with horizontallist widget.

**Comment by Haroon-KA** [comment]
@m0hamm3d-ac , Thank you for the pointer . I had cross checked the implementation to see that both the keyboard and horizontal list widget is appended to the verticallist

Please find below the code here : 

`_onBeforeRender: function(ev) {
                this.emailVerticalList.insertChildWidget(0, this.backButton);
                this.emailVerticalList.insertChildWidget(1, this.emailInputButton);
                this.emailVerticalList.insertChildWidget(2, this.emailErrorLabel);
                this.emailVerticalList.insertChildWidget(3, this.keyboard);

                this.emailOptionsHorizontalList.insertChildWidget(0, this.upperCaseButton);
                this.emailOptionsHorizontalList.insertChildWidget(1, this.lowerCaseButton);
                this.emailOptionsHorizontalList.insertChildWidget(2, this.specialCharacterButton);

                this.emailVerticalList.insertChildWidget(4, this.emailOptionsHorizontalList)
                this.emailVerticalList.insertChildWidget(5, this.navButton);
            },`

I am not able to understand what I am doing wrong here :(

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
