### ISSUE TITLE
Are there any plans to add package-lock.json into repo?

### ISSUE THREAD

**Issue by m0hamm3d-ac** [bbc/tal#499]
Is there any plans to add the package-lock.json by the lead contributors to ensure a locked down version of dependencies?

**Comment by m0hamm3d-ac** [comment]
https://github.com/bbc/tal/commit/dd6e50d4cc6349392e4ad193e861f5b757e341c1 has a package-lock.json which fixes the npm test issue. Can we pls get this merged to master..

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
