### ISSUE TITLE
Horizontal carousel inside vertical carousel is not working 

### ISSUE THREAD

**Issue by Arunprasanth** [bbc/tal#500]
Hi, 
I have n number of dynamically created horizontal carousels I am trying to add all these carousels to a vertical carousel to handle the scroll issue in tal framework. But the mentioned approach is not working in my case. I have tested the same with buttons, I have created n number of buttons and passed as arguments to the vertical carousel and its works nicely, issue is only appear when I try to add horizondal carousel inside a vertical carousel. 

No error is coming. Below is the horizondal  carousel item element I am getting  while i console from the formattor method 

![capture](https://user-images.githubusercontent.com/17898273/38187193-38344370-3674-11e8-8ff2-bbd91333dc5f.PNG)

Horizonal carousels working fine whenI add them as vertical list elements , But doesnt work when I add them as vertical carousel elements. 
Please help me to resolve this issue

**Comment by Flyover-ArtSk** [comment]
Did you solver your problem? I got same problem

**Comment by Arunprasanth** [comment]
@Flyover-ArtSk  Yes I have solved my problem. I have created my own control for doing the same. I have used the help of vertical list. Instead of horizontal carousel inside vertical I have used vertical list with horizontal carousel.

**Comment by kukulaka** [comment]
Am glad you solved your issue @Arunprasanth. 😄 

We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
