### ISSUE TITLE
Client side rendering only

### ISSUE THREAD

**Issue by boris-felix** [bbc/tal#504]
Hi here,

I would like to know if TAL can only work on a server side rendering model ? The project i am working on will have to potentially face a lot of traffic and we would like to avoid having to deal with any web server configuration as nginx for example. As a solution, we are currently hosting all our web applications on an S3 bucket with only the html files and the static assets to render and we are doing all the routing part with javascript ( React Router for instance ). Does something similar would be possible with TAL ?

After doing some researches, i was thinking of hosting my application somewhere on S3 and then launching it from a main TAL application like explained here : http://bbc.github.io/tal/other/launching.html.

Do you think that this is a good approach ?

Thank you for your help.

**Comment by kukulaka** [comment]
Hi @boris-felix, thank you for your question. We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
