### ISSUE TITLE
TAL on Samsung Tizen TV

### ISSUE THREAD

**Issue by kindaichima** [bbc/tal#515]
I have a project that need to implement an live/VOD streaming on Samsung Tizen TV (3.0+). I think TAL may be a good choice but I have some questions that would like to clarify. 

1. As far as I know TAL is based on nodeJS, Does Samsung TV support nodeJS application that is wrapped in the deployment package, or we have to create a web server remotely and let the TV application to call the server side page? Is it the same deployment step when iPlayer launched in Samsung Tizen TV?

2. The stream that we are using are MPEG-DASH with DRM support (Playready/ Widewine). Does TAL uses Samsung native player/shaka player or TAL tailor made player? Is it possible for us to turn into Shaka Player by modifying TAL's code?

Thanks a lot!

**Comment by rosswilson** [comment]
Hi @kindaichima,

TAL is almost entirely a client-side JS framework, but you're correct that there is some server-side Node.js code provided. TAL applications are deployed like any other JS single-page application, and the application is initially served up using a HTML page. This HTML page (sometimes referred to as the _base-page_) can be generated using the provided Node.js helper functions. Alternatively you can use any server-side language/framework capable of rendering the necessary HTML.

You can take a look at the [TAL Example app](https://github.com/bbc/talexample), specifically the [Mustache template](https://github.com/bbc/talexample/blob/master/views/index.mustache) to see what is required to launch a TAL app.

Regarding DRM, TAL currently has no support for DRM (either MS PlayReady or Widewine). There is ongoing development around video playback, so I will mention this GitHub Issue internally and see if I can get a more informed answer regarding your question.

**Comment by kindaichima** [comment]
Thanks for that. On the other hand, do you have any timeline to support DRM using TAL ?

**Comment by tsadler1988** [comment]
@kindaichima Apologies for the delay in responding. DRM is not on TAL's roadmap I'm afraid.
