### ISSUE TITLE
Minor err in manual

### ISSUE THREAD

**Issue by Kogoruhn** [bbc/tal#516]
Hi! [Manual](https://bbc.github.io/tal/overview/device-configuration.html) says that 

> The framework supports the following log types, in ascending severity
> 
> log
> debug
> info
> warn
> error

let's see the source [devices/device](https://bbc.github.io/tal/jsdoc/devices_device.js.html):

```
 switch (level) {
 case 'all':
 case 'debug':
     filteredLogging.debug = loggingMethods.debug;
 case 'info':
     filteredLogging.info = loggingMethods.info;
     filteredLogging.log = loggingMethods.log;
 case 'warn':
     filteredLogging.warn = loggingMethods.warn;
 case 'error':
     filteredLogging.error = loggingMethods.error;
 }
```

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
