### ISSUE TITLE
Play live streaming on non-native HLS browsers.

### ISSUE THREAD

**Issue by mccorry** [bbc/tal#517]
Hello unbelievable team of programmers. 😄 

What would be the way to play live streaming for example in firefox that does not have native hls support?

**Comment by tsadler1988** [comment]
Hi @mccorry, TAL's media player does not add support for any streaming technologies I'm afraid. It provides a abstraction for HTML5, CE-HTML, and Samsung media players, and makes using them a bit more robust, but it's up the underlying player to support the media.

You could in theory use Media Source Extensions to add HLS support (https://github.com/video-dev/hls.js/ is one example), but I believe there are licensing implications if you provide HLS decoding ([this article](http://www.overdigital.com/2012/04/17/the-hidden-licensing-costs-of-hls-video-playback/) seems to explain it).
