### ISSUE TITLE
ammend the navigation behaviour in the carousel component

### ISSUE THREAD

**Issue by pawelgliwinski** [bbc/tal#519]
Hi,

I would like to achieve to amend the carousel navigation behaviour. Assume I have 15 elements but only 8 of those are visible within the mask. The focus is located on the far left of the mask. While pressing right button I would like the focus first move to the right and when it reaches the right border of the mask the content underneath should start moving left. Could you suggest on how this could be achieved ?

**Comment by rafcourt** [comment]
I have a listener on the beforealign event. In the callback I re-calculate the alignment point based on the intended tile index, in your case 0-7, then I make a call to setNormalisedAlignPoint(newNormalisedAlignmentPoint). 
However, I am having an issue with the position accuracy of the widgetstrip element. There is a 0.333px discrepancy between my calculation and TAL's during the scrolling process, resulting in a 'shuddering' of the carousel.

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
