### ISSUE TITLE
TAL Formatter usage causing memory leaks

### ISSUE THREAD

**Issue by Bala1908** [bbc/tal#537]
When we are using TAL formatter to create carousel,
we are facing memory leaks with class objects which created by TAL frame work.
So please guide us with a solution to resol
![TaLBBC_FormatterObjMemoryIssue](https://user-images.githubusercontent.com/79853622/109974132-416c3200-7d1f-11eb-8f6e-b08b4c25dd21.PNG)
![TALBBC_ObjectsMemoryIssue](https://user-images.githubusercontent.com/79853622/109974140-429d5f00-7d1f-11eb-80c0-5a98abd4fdb0.PNG)

ve the issue.

**Comment by Bala1908** [comment]
Hi Team,
please find the sample code we have used and memory consumption based on the data we are using.
![image](https://user-images.githubusercontent.com/79853622/110637612-9a324380-81d3-11eb-8d6c-6f7e33e1af65.png)

sample we have used is in below link,
https://github.com/bbc/talexample

**Comment by kukulaka** [comment]
Hi @Bala1908, am sorry that no one got back to you on this.

We have deprecated this project and there are no plans for active development going forward, so this issue has been closed.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
