### ISSUE TITLE
how to start?

### ISSUE THREAD

**Issue by allegfede** [bbc/tal#538]
Hello.
I'm really new to the smart tv app world.
I made some simple applications with android studio and but i usually code in python and gambas (a fun rad language for linux pcs), so i really need some starting point to get in TAL :D

do you propose some kind of coding enviroment/ide?

i know, noob question :-(

**Comment by kukulaka** [comment]
Hi @allegfede, am sorry that no one got back to you on this. For JavaScript development, I'm a fan of [VS Code ](https://code.visualstudio.com) as it has lots of very handy extensions. Of course, there are different IDE's out there so try a few and see which one you prefer 😄 

We have deprecated this project and there are no plans for active development going forward, so this issue has been closed. 

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).
