### ISSUE TITLE
what is replacing the deprecated function getTextHeight()

### ISSUE THREAD

**Issue by meghamalamukherjee** [bbc/tal#540]
The function **getTextHeight()** inside browserdevice class (the file path : https://github.com/bbc/tal/blob/master/static/script/devices/browserdevice.js#L428 ) 
is mentioned **deprecated**. But, I couldn't find the functionality that is replacing it. 
Please let me know what is replacing this function.
Any help will be really appreciated.
Thanks in advance

**Comment by meghamalamukherjee** [comment]
any update on this.

**Comment by meghamalamukherjee** [comment]
Hi, Long waiting for a feedback on this. Please reply on this.

**Comment by kukulaka** [comment]
Hi @meghamalamukherjee, apologies that no one got back to you on this in good time. 

TAL is no longer a maintained project. Please see our [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022). We apologise that we have not been more active in keeping the community informed on the status of this project.

We are looking to set up a mailing list so we can keep in contact with TAL users. We will share this address once this has been created.
