### ISSUE TITLE
 PWA Compatibility

### ISSUE THREAD

**Issue by Wotan6891** [bbc/tal#541]
Hello,

And thanks for such a great project.

I would like to know if in the future you are going to add support for PWA, Progressive Web Applications?

since it would be great to use the same code that is used in Web Pages, and Applications for App Store and Google Play. It can also be used on Smart TVs.

This article is a reference that could be made:

https://blog.hao.dev/creating-tv-apps-with-web-technology

Thanks and regards.

**Comment by kukulaka** [comment]
Hi @Wotan6891 this project is now [deprecated](https://github.com/bbc/tal#deprecation-announcement-12122022), so am closing this issue. 

Thank you for your interest. We should have further news soon.
