### ISSUE TITLE
How to complie for LG WebOS TV?

### ISSUE THREAD

**Issue by titus-shoats** [bbc/tal#543]
Is there a way to compile this for LG WebOS TV Simulator? How do we compile for a tv device such as Samsung, tizen, lg, etc..?
Any advice or help with this?

**Comment by rafcourt** [comment]
You will have to use fs to save the rendered output from mustache.

**Comment by kukulaka** [comment]
Please note that we are closing all outstanding issues in line with our [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022). 
We apoligise that we have not been more active in this project and hope to the keep more engaged with the community going forward.

There will be a mailing list that TAL users can join. We will share the details of this very soon.
